version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "5173:5173"  
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps with file change detection inside Docker
    command: npm run dev

  e2e:
    image: cypress/included:14.0.1  # Official Cypress image with Node included
    depends_on:
      - react-app
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e                
      - /e2e/node_modules         
    environment:
      - CYPRESS_baseUrl=http://react-app:5173  # Connect Cypress to the React container
    entrypoint: sh -c "npm install && CYPRESS_SPEC_FILE=**/* npm run run:cypress"